# Generated by Django 3.0 on 2020-08-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200822_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='null', upload_to='items/'),
            preserve_default=False,
        ),
    ]
